### ISSUE TITLE
Better Sequence Reconciler

### ISSUE THREAD

**Issue by HereIsKevin** [HereIsKevin/fluid#1]
Currently, the reconciler for sequences is very basic, using only the following primitive steps:

1. Make sure the sequence is short enough
2. Make sure the sequence is long enough
3. Make sure all the items in the sequence are updated

This approach works relatively well most things, but for removing items in between, this is very slow. To improve this, the following approaches could work:

- Add back support for keys for sequences (used to have them a while ago)
- Improve the reconciliation algorithm to check for small removals

**Comment by HereIsKevin** [comment]
Fluid's current rendering system is very fast for non-keyed rendering, but it is too brittle for keyed rendering to be added back again. I'm considering doing at least a partial rewrite.

**Comment by HereIsKevin** [comment]
I'm planning on adding directives or plugins for implementing this. Currently planned for v0.4.0 or later.

**Comment by guiprav** [comment]
I'm very curious for those PRs (: Good luck! (My baby [Dominant](https://github.com/guiprav/dominant) doesn't even implement keyed map yet, I wonder for how long I can get away without it, but I also have plans to implement it soon).

**Comment by HereIsKevin** [comment]
Currently planned syntax:

```javascript
render(
  target,
  html`
    <div>
      ${values.map((value) => [
        value.id, // key for diffing
        html`<div>${value.count}</div>`,
      ])}
    </div>
  `
);
```

**Comment by HereIsKevin** [comment]
Implemented basic keyed sequence reconciler with d6984a4faddb6840b3b5146bbca77773cccb0984 without proper node swapping.

**Comment by HereIsKevin** [comment]
Fully implemented with 8ccf1499a8fd6f7bedfdfdad548883daea2f5747 with proper node swapping! 🎉

**Comment by guiprav** [comment]
Hi, @HereIsKevin! It's not clear to me what the update process looks like. I can see how `renderArrangement` can render a sequence of elements with markers in place the first time, but when it's time to update (e.g. an element has moved inside the array), what code paths are hit? Does `renderArrangement` run again or only parts of it based on the markers?

I'm just curious, don't mind me unless you can find a  little time and energy to talk to this Internet stranger  (:

**Comment by HereIsKevin** [comment]
When it's time to update, the giant while loop is run. The general algorithm goes like this:

1. If the two keys are the same, update the template and move on.
2. If the two keys are different and there is still space for inserting, try using a cached sequence, then try stealing a sequence from somewhere else, and finally, create the sequence.
3. If the two keys are different and there is no space for inserting, remove the current sequence and cache it.
